### ISSUE TITLE
Issues running Telemanom using SMD Dataset

### ISSUE THREAD

**Issue by fahmirzldi** [TimeEval/TimeEval#137]
Hi!

I followed the tutorial and successfully ran lof on Daphnet dataset. However, when I tried to run Telemanom using SMD Dataset, I met `IndexError: boolean index did not match indexed array along dimension 0` Error

Is there any configuration that I didn't set correctly?

Also kindly let me know if there is any other data to help reproduce the error.

Thank you in advance

**Code**
```
#!/usr/bin/env python3

from pathlib import Path

from timeeval import TimeEval, MultiDatasetManager, DefaultMetrics, Algorithm, TrainingType, InputDimensionality, ResourceConstraints
from timeeval.adapters import DockerAdapter
from timeeval.params import FixedParameters
from timeeval.resource_constraints import GB


def main():
    ####################
    # Load and select datasets
    ####################
    dm = MultiDatasetManager([
        Path("./timeeval-datasets")  # e.g. ./timeeval-datasets
        # you can add multiple folders with an index-File to the MultiDatasetManager
    ])
    # A DatasetManager reads the index-File and allows you to access dataset metadata,
    # the datasets itself, or provides utilities to filter datasets by their metadata.
    # - select ALL available datasets
    # datasets = dm.select()
    # - select datasets from Daphnet collection
    datasets = dm.select(collection="SMD")
    # - select datasets with at least 2 anomalies
    # datasets = dm.select(min_anomalies=2)
    # - select multivariate datasets with a maximum contamination of 10%
    # datasets = dm.select(input_dimensionality=InputDimensionality.MULTIVARIATE, max_contamination=0.1)
    # limit to 5 datasets for this example
    datasets = datasets[2:3]
    print(datasets)

    ####################
    # Load and configure algorithms
    ####################
    # create a list of algorithm-definitions, we use a single algorithm in this example
    algorithms = [Algorithm(
        name="telemanom",
        main=DockerAdapter(
            image_name="ghcr.io/timeeval/telemanom",
            tag="0.3.0",  # please use a specific tag instead of "latest" for reproducibility
            skip_pull=True  # set to True because the image is already present from the previous section
        ),
        # The hyperparameters of the algorithm are specified here. If you want to perform a parameter
        # search, you can also perform simple grid search with TimeEval using FullParameterGrid or
        # IndependentParameterGrid.
        param_config=FixedParameters({
            "n_neighbors": 50,
            "random_state": 42
        }),
        # required by DockerAdapter
        data_as_file=True,
        # You must specify the algorithm metadata here. The categories for all TimeEval algorithms can
        # be found in their README or their manifest.json-File.
        # UNSUPERVISED --> no training, SEMI_SUPERVISED --> training on normal data, SUPERVISED --> training on anomalies
        # if SEMI_SUPERVISED or SUPERVISED, the datasets must have a corresponding training time series
        training_type=TrainingType.SEMI_SUPERVISED,
        # MULTIVARIATE (multidimensional TS) or UNIVARIATE (just a single dimension is supported)
        input_dimensionality=InputDimensionality.MULTIVARIATE
    )]

    ####################
    # Configure evaluation run
    ####################
    # set the number of repetitions of each algorithm-dataset combination (e.g. for runtime measurements):
    repetitions = 1
    # set resource constraints
    rcs = ResourceConstraints(
        task_memory_limit = 8 * GB,
        task_cpu_limit = 12,
    )
    
    # create TimeEval object and pass all the options
    timeeval = TimeEval(dm, datasets, algorithms,
        repetitions=repetitions,
        resource_constraints=rcs,
        # you can choose from different metrics:
        metrics=[DefaultMetrics.ROC_AUC, DefaultMetrics.FIXED_RANGE_PR_AUC],
    )

    # With run(), you can start the evaluation.
    timeeval.run()
    # You can access the overall evaluation results with:
    results = timeeval.get_results()
    print(results)

    # Detailed results are automatically stored in your current working directory at ./results/<datestring>.


if __name__ == "__main__":
    main()
```

**Result**
```
Running PREPARE phase
Running EVALUATION phase
Evaluating:   0%|                                                                                        | 0/1 [00:00<?, ?it/s]Exception occurred during the evaluation of telemanom on the dataset Dataset(datasetId=('SMD', 'machine-1-3'), dataset_type='real', training_type=<TrainingType.SEMI_SUPERVISED: 'semi-supervised'>, length=23703, dimensions=38, contamination=0.0344682107750073, min_anomaly_length=3, median_anomaly_length=46, max_anomaly_length=225, period_size=nan, num_anomalies=12).
Traceback (most recent call last):
  File "C:\Users\fahmi\anaconda3\envs\timeeval\lib\site-packages\timeeval\timeeval.py", line 359, in _run
    result = exp.evaluate()
  File "C:\Users\fahmi\anaconda3\envs\timeeval\lib\site-packages\timeeval\_core\experiments.py", line 140, in evaluate
    raise e
  File "C:\Users\fahmi\anaconda3\envs\timeeval\lib\site-packages\timeeval\_core\experiments.py", line 135, in evaluate
    raise last_exception
  File "C:\Users\fahmi\anaconda3\envs\timeeval\lib\site-packages\timeeval\_core\experiments.py", line 116, in evaluate
    score = metric(y_true, y_scores)
  File "C:\Users\fahmi\anaconda3\envs\timeeval\lib\site-packages\timeeval\metrics\metric.py", line 42, in __call__
    y_true, y_score = self._validate_scores(y_true, y_score, **kwargs)
  File "C:\Users\fahmi\anaconda3\envs\timeeval\lib\site-packages\timeeval\metrics\metric.py", line 93, in _validate_scores      
    y_score[penalize_mask] = (~np.array(y_true[penalize_mask], dtype=bool)).astype(np.int_)
IndexError: boolean index did not match indexed array along dimension 0; dimension is 23703 but corresponding boolean dimension is 23443
Evaluating: 100%|███████████████████████████████████████████████████████████████████████████████| 1/1 [14:48<00:00, 888.53s/it] 
Running FINALIZE phase
FINALIZE phase done.
          Stored results at C:\DATA\ACADEMIC\LAB STUDIES\Project\ITRC\Code\TimeEval\results\2024_04_08_12_49_47\results.csv.    
          Overall runtime of this TimeEval run: 888.5417675971985 seconds

The results contain errors which are filtered out for the final aggregation. To see all results, call .get_results(aggregated=False)
Empty DataFrame
Columns: [ROC_AUC_mean, FIXED_RANGE_PR_AUC_mean, train_main_time_mean, execute_main_time_mean, repetitions]
Index: []
```

**Comment by CodeLionX** [comment]
Dear @fahmirzldi,

Telemanom outputs anomaly scores for windows, [so the output requires post-processing](https://github.com/TimeEval/TimeEval-algorithms/tree/main/telemanom#notes). This can either be done by (a) adding it to your algorithm definition or by (b) using the algorithm definitions provided by TimeEval.

### (a) Add post-processing-function manually

```bash
from timeeval.utils.window import ReverseWindowing
[...]
# post-processing for telemanom
def post_telemanom(scores: np.ndarray, args: dict) -> np.ndarray:
    size = args.get("hyper_params", {}).get("window_size", 250) + args.get("hyper_params", {}).get("prediction_window_size", 10)
    return ReverseWindowing(window_size=size + 1).fit_transform(scores)
[...]
    ####################
    # Load and configure algorithms
    ####################
    # create a list of algorithm-definitions, we use a single algorithm in this example
    algorithms = [Algorithm(
        name="telemanom",
        main=DockerAdapter(
            image_name="ghcr.io/timeeval/telemanom",
            tag="0.3.0",  # please use a specific tag instead of "latest" for reproducibility
            skip_pull=True  # set to True because the image is already present from the previous section
        ),
        postprocess=post_telemanom,
[...]
```

### (b) Use provided algorithm-definition [`timeeval.algorithms.telemanom`](https://timeeval.readthedocs.io/en/latest/api/timeeval.algorithms.html#timeeval-algorithms-telemanom)

```bash
from timeeval.algorithms import telemanom
[...]
    ####################
    # Load and configure algorithms
    ####################
    # create a list of algorithm-definitions, we use a single algorithm in this example
    algorithms = [
        telemanom(params=FixedParameters({
            "n_neighbors": 50,
            "random_state": 42
        }))
    ]

    ####################
    # Configure evaluation run
    ####################
[...]
```

**Comment by fahmirzldi** [comment]
It worked! I somehow miss the requirement to add the preprocessing.

Thank you for the solution.
